[build]
  base = "" # Leave this empty if your package.json is in the root directory
  publish = "public" # Directory where the built files are located
  command = "npm run build"

[functions]
  directory = "netlify/functions"
